version: '3'
services:
  app:
    image: node:18.15
    container_name: node-server
    command: bash -c "yarn && yarn dev"
    restart: unless-stopped
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
