name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Install Dependencies
      run: yarn install

    - name: Run tests
      run: yarn test

    - name: Build
      if: ${{ success() && github.event_name == 'push' }}
      run: yarn build

    - name: Create deployment package
      if: ${{ success() && github.event_name == 'push' }}
      run: zip -r deploy.zip . -x ".git/*" -x ".github/*" -x ".vscode/*" -x ".hursky/*" -x ".mock/*" -x ".__test__/*"

    - name: Deploy to AWS
      if: ${{ success() && github.event_name == 'push' }}
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.AWS_APP_NAME }}
        environment_name: ${{ secrets.AWS_APP_ENV_NAME }}
        existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
        version_label: ${{ github.run_id }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        use_existing_version_if_available: true
